apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudops-pro-ingress
  labels:
    app: cloudops-pro
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: cloudops-pro.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudops-pro-service
            port:
              number: 80 