apiVersion: v1
kind: Service
metadata:
  name: cloudops-pro-service
  labels:
    app: cloudops-pro
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cloudops-pro 